routes/web.php
<?php

use App\Http\Controllers\TR\Test\Test_TRController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WhDepsController;
use App\Http\Controllers\JobDatasController;
use App\Http\Controllers\WhActsContoller;
// use App\Http\Controllers\HomeController;
use App\Http\Controllers\RegisterController;
// use App\Http\Controllers\LoginController;
// use App\Http\Controllers\LogoutController;
use App\Http\Controllers\ProductInputController;
use App\Http\Controllers\UserTypeController;
use App\Http\Controllers\ForkliftController;
use App\Http\Controllers\FlocationController;
use App\Http\Controllers\FpeopleController;
use App\Http\Controllers\WhActTypeController;
use App\Http\Controllers\FLogController;
use App\Http\Controllers\RecvRmOtherPlansController;
use App\Http\Controllers\RmManualController;
use App\Http\Controllers\StProductController;
use App\Http\Controllers\StWhBeginController;
use App\Http\Controllers\StBrokerController;
use App\Http\Controllers\StReceiveController;
use App\Http\Controllers\StWhithdrawController;


use App\Http\Controllers\FS\ShiftController;
use App\Http\Controllers\FS\ProductController;
use App\Http\Controllers\FS\StoreController;
use App\Http\Controllers\FS\StepController;
use App\Http\Controllers\FS\StepTgController;
use App\Http\Controllers\FS\LoseTypeController;
use App\Http\Controllers\FS\ToReuseController;
use App\Http\Controllers\FS\WashController;
use App\Http\Controllers\FS\DryController;
use App\Http\Controllers\FS\ShineController;
use App\Http\Controllers\FS\ChooseBoxController;
use App\Http\Controllers\FS\StockController;
use App\Http\Controllers\FS\ToUseController;
use App\Http\Controllers\FS\LoseController;
use App\Http\Controllers\FS\TargetController;
use App\Http\Controllers\FS\TargetProductController;
use App\Http\Controllers\FS\ReportController;

//Stock FS WH part
use App\Http\Controllers\Fs\FsWhsController;
use App\Http\Controllers\Fs\FsStocksController;
use App\Http\Controllers\FS\FsReportsController;

use App\Http\Controllers\HandheldImportsController;
use App\Http\Controllers\TR\CalendarController;
//Track Schedule Management
use App\Http\Controllers\TR\TrucksController;
use App\Http\Controllers\TR\ImpDeliveryPlansController;
use App\Http\Controllers\TR\ScheduleTrucksController;
use App\Http\Controllers\TR\TailsController;
use App\Http\Controllers\TR\VesselLinesController;
use App\Http\Controllers\TR\HolidaysController;
use App\Http\Controllers\TR\SumaryController;
use App\Http\Controllers\TR\WeekendsController;

//TEST WHRM
use App\Http\Controllers\WHRM\BeanController;
use App\Http\Controllers\WHRM\TestController;
use App\Http\Controllers\WHRM\BananaController;
use App\Http\Controllers\WHRM\setting\WhRmBrokerAreaController;
use App\Http\Controllers\WHRM\WhRmController;
use App\Http\Controllers\WHRM\WhRmDeleteController;
use App\Http\Controllers\WHRM\WhRmEmailController;
use App\Http\Controllers\WHRM\WhRmImportFileController;
use App\Http\Controllers\WHRM\WhRmReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::group(['namespace' => 'App\Http\Controllers'], function () {
    /**
     * Home Routes
     */
    Route::get('/', 'HomeController@index')->name('home.index');

    Route::resource('whdeps', 'WhDepsController');
    Route::resource('jobdatas', 'JobDatasController');

    Route::get('/whacts/planvsactrpt/{date}', 'WhActsContoller@planvsactrpt');

    Route::group(['middleware' => ['guest']], function () {
        /**
         * Register Routes
         */
        Route::get('/register', 'RegisterController@show')->name('register.show');
        Route::post('/register', 'RegisterController@register')->name('register.perform');
        /**
         * Login Routes
         */
        Route::get('/login', 'LoginController@show')->name('login.show');
        Route::post('/login', 'LoginController@login')->name('login.perform');
    });

    Route::group(['middleware' => ['auth']], function () {
        /**
         * Logout Routes
         */
        Route::get('/logout', 'LogoutController@perform')->name('logout.perform');
    });
});

Route::get('/user/delete/{id}', [RegisterController::class, 'destroy'])->name('user_delete');
Route::resource('user', RegisterController::class);

Route::get('/pd_input/importExportView', [ProductInputController::class, 'importExportView'])->name('pd_import_export');
Route::post('/pd_input/import/{tbl}', [ProductInputController::class, 'import'])->name('pd_import');
Route::get('/pd_input/reportView', [ProductInputController::class, 'reportView'])->name('pd_report');
Route::get('/pd_input/report_show', [ProductInputController::class, 'report_export'])->name('pd_show');
Route::get('/pd_input/file_delete/{id}', [ProductInputController::class, 'destroy'])->name('pd_delete');    //delete file
Route::get('/pd_input/list_delete/{type}/{id}', [ProductInputController::class, 'list_destroy'])->name('pd_list_delete');    //delete list
Route::get('/pd_input/mail/{tbl}/{date_to}', [ProductInputController::class, 'sentmail'])->name('pd_sentmail');
Route::get('/pd_input/sum_mail/{date_to}', [ProductInputController::class, 'sum_mail']);
Route::get('/pd_input/sum_mail_month', [ProductInputController::class, 'sum_mail_month']);
Route::resource('pd_input', ProductInputController::class);

Route::resource('/setting/user_type', UserTypeController::class);

Route::get('/setting/forklift/importExportView', [ForkliftController::class, 'importExportView'])->name('forklift_import_export');
Route::post('/setting/forklift/import', [ForkliftController::class, 'import'])->name('forklift_import');
Route::resource('/setting/forklift', ForkliftController::class);

Route::resource('/setting/location', FlocationController::class);
Route::resource('/setting/people', FpeopleController::class);

Route::get('/setting/WhAct_type/importExportView', [WhActTypeController::class, 'importExportView'])->name('WhAct_type_import_export');
Route::post('/setting/WhAct_type/import', [WhActTypeController::class, 'import'])->name('WhAct_type_import');
Route::resource('/setting/WhAct_type', WhActTypeController::class);

Route::get('/FL/FL_del/{date}', [FLogController::class, 'destroy_date'])->name('FL_del');    //delete file
Route::get('/FL/importExportView', [FLogController::class, 'importExportView'])->name('FL_import_export');
Route::post('/FL/import', [FLogController::class, 'import'])->name('FL_import');
Route::get('/FL/reportView', [FLogController::class, 'reportView'])->name('FL_report');
Route::get('/FL/report_show', [FLogController::class, 'report_export'])->name('FL_show');
// Route::get('/FL/mail/{date_to}', [FLogController::class, 'sentmail'])->name('FL_sentmail');
Route::get('/FL/mailView', [FLogController::class, 'mailView'])->name('FL_mail');
Route::get('/FL/sent_mail', [FLogController::class, 'sent_mail'])->name('FL_sent_mail');
Route::get('/FL/atc_search', [FLogController::class, 'selectfl'])->name('FL_autocomplete');
Route::get('/FL/cmb_area', [FLogController::class, 'cmb_area'])->name('FL_area');
Route::get('/FL/cmb_person', [FLogController::class, 'cmb_person'])->name('FL_person');
Route::get('/FL/cmb_broken', [FLogController::class, 'cmb_broken'])->name('FL_broken');
Route::resource('FL', FLogController::class);


Route::get('/recvrmotherplans/changeStatus/{id}', [RecvRmOtherPlansController::class, 'changeStatus'])->name('recvrmotherplans.changestatus');
Route::resource('recvrmotherplans', RecvRmOtherPlansController::class);

Route::get('/wh_act/importExportView', [WhActsContoller::class, 'importExportView'])->name('wh_act_import_export');
Route::post('/wh_act/import_plan', [WhActsContoller::class, 'import_plan'])->name('wh_act_import_plan');
Route::post('/wh_act/import_act', [WhActsContoller::class, 'import_act'])->name('wh_act_import_act');
Route::get('/wh_act/reportView', [WhActsContoller::class, 'reportView'])->name('wh_act_report');
Route::get('/wh_act/report_show', [WhActsContoller::class, 'report_export'])->name('wh_act_show');
Route::get('/wh_act/mailView', [WhActsContoller::class, 'mailView'])->name('wh_act_mail');
Route::get('/wh_act/sent_mail', [WhActsContoller::class, 'sent_mail'])->name('wh_act_sent_mail');
Route::get('/wh_act/del/{date}', [WhActsContoller::class, 'destroy_date'])->name('wh_act_del');    //delete file ลบทั้ง plan และ act จากปุ่มถังขยะหน้า index
Route::post('/wh_act/del_import', [WhActsContoller::class, 'destroy_import'])->name('wh_act_del_import');    //ลบโดยเลือกว่าลบจากอะไร plan/act ที่หน้า import
// Route::get('/wh_act/note/{st}/{pd}/{note}', [WhActsContoller::class, 'save_note']);
Route::get('/wh_act/note', [WhActsContoller::class, 'save_note']);
Route::resource('wh_act', WhActsContoller::class);

Route::get('/wh_rm/importExportView', [RmManualController::class, 'importExportView'])->name('wh_rm_import_export');
Route::post('/wh_rm/import_sap', [RmManualController::class, 'import_sap'])->name('wh_rm_import_sap');
Route::get('/wh_rm/export_manual', [RmManualController::class, 'export_manual'])->name('wh_rm_export_manual');
Route::post('/wh_rm/import_manual', [RmManualController::class, 'import_manual'])->name('wh_rm_import_manual');
Route::post('/wh_rm/export_sap', [RmManualController::class, 'import_comment'])->name('wh_rm_import_comment');
Route::get('/wh_rm/reportView', [RmManualController::class, 'reportView'])->name('wh_rm_report');
Route::get('/wh_rm/report_show', [RmManualController::class, 'report_export'])->name('wh_rm_show');
Route::get('/wh_rm/mailView', [RmManualController::class, 'mailView'])->name('wh_rm_mail');

app/Models/FS/ChooseBox.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ChooseBox extends Model
{
    use HasFactory;

    protected $fillable = [
        'to_date','shift','to_reuse_id','pallet_no','quantity','note','status', 'user_id',
    ];

    public function to_reuse()
    {
        return $this->belongsTo(ToReuse::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
  
    public function stocks()
    {
        return $this->hasMany(Stock::class);
    }   
    
}

app/Models/FS/Dry.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dry extends Model
{
    use HasFactory;

    protected $fillable = [
        'to_date','shift','wash_id','dry_no','round_no','sort','quantity','note','status', 'user_id',
    ];

    public function wash()
    {
        return $this->belongsTo(Wash::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function stocks()
    {
        return $this->hasMany(Stock::class);
    }    
}

app/Models/FS/FsHwLoc.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FsHwLoc extends Model
{
    use HasFactory;

    protected $fillable = ['fs_wh_id','name','desc','row','col','level','product_id','status', ];

    public function fswh()
    {
        return $this->belongsTo(FsHwMain::class, 'fs_wh_id');
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }

    public function fswhstocks()
    {
        return $this->hasMany(FsWhStock::class, 'fs_wh_loc_id');
    }

    public function fswhtrands()
    {
        return $this->hasMany(FsWhTranDs::class, 'fs_wh_loc_id');
    }

    public function fsstocks()
    {
        return $this->hasMany(FsStock::class, 'fs_wh_loc_id');
    }

}

app/Models/FS/FsHwMain.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FsHwMain extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'desc', 'row', 'col', 'level', 'all_loc', 'user_id',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function fswhlocs()
    {
        return $this->hasMany(FsHwLoc::class, 'fs_wh_id');
    }
}

app/Models/FS/FsStock.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FsStock extends Model
{
    use HasFactory;

    protected $fillable = [
        'fs_wh_loc_id', 'product_id', 'pallet', 'volumn', 'desc', 'status', 'stock_id', 'user_id', 'to_date'
    ];

    public function fsloc()
    {
        return $this->belongsTo(FsHwLoc::class, 'fs_wh_loc_id');
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }

    public function stock()
    {
        return $this->belongsTo(Stock::class, 'stock_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/FS/FsStockTrans.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FsStockTrans extends Model
{
    use HasFactory;

    protected $fillable = [
        'fs_wh_loc_id', 'product_id', 'pallet', 'volumn', 'desc', 'status', 'stock_id', 'user_id', 'to_date'
    ];

    public function fsloc()
    {
        return $this->belongsTo(FsHwLoc::class, 'fs_wh_loc_id');
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }

    public function stock()
    {
        return $this->belongsTo(Stock::class, 'stock_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/FS/FsWhStock.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FsWhStock extends Model
{
    use HasFactory;

    protected $fillable = [
        'fs_wh_loc_id', 'product_id', 'pallet', 'volumn', 'desc', 'status', 'stock_id', 'user_id', 'to_date'
    ];

    public function fsloc()
    {
        return $this->belongsTo(FsHwLoc::class, 'fs_wh_loc_id');
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }
    
    public function stock()
    {
        return $this->belongsTo(Stock::class, 'stock_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Models/FS/FsWhTranDs.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FsWhTranDs extends Model
{
    use HasFactory;

    protected $fillable = [
        'fs_wh_tran_m_id', 'fs_wh_loc_id', 'product_id', 'pallet', 'volumn', 'desc', 'status', 'stock_id', 'user_id', 'to_date'
    ];

    public function fsloc()
    {
        return $this->belongsTo(FsHwLoc::class, 'fs_wh_loc_id');
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id');
    }

    public function stock()
    {
        return $this->belongsTo(Stock::class, 'stock_id');
    }
    
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Models/FS/FsWhTranMs.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class FsWhTranMs extends Model
{
    use HasFactory;

    protected $fillable = [
        'tran_dt', 'tran_type', 'desc', 'user', 'status', 'user_id',
    ];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function fswhtrands()
    {
        return $this->hasMany(FsWhTranDs::class, 'fs_wh_tran_m_id');
    }
}

app/Models/FS/Lose.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Lose extends Model
{
    use HasFactory;

    protected $fillable = [
        'to_date','shift','step_id','refer_id','lose_type_id','quantity','note','lose_stock', 'user_id',
    ];

    public function step()
    {
        return $this->belongsTo(Step::class);
    }

    public function lose_type()
    {
        return $this->belongsTo(LoseType::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

app/Models/FS/LoseType.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class LoseType extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'name',
    ];

    public function loses()
    {
        return $this->hasMany(Lose::class);
    }
}

app/Models/FS/Product.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
    
    protected $fillable = [
        'name','desc','status_wash','status_check',
    ];

    public function to_reuses()
    {
        return $this->hasMany(ToReuse::class);
    }
    
    // public function target_products()
    // {
    //     return $this->hasMany(TargetProduct::class);
    // }
}

app/Models/FS/Shift.php
<?php

namespace App\Models\FS;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Shift extends Model
{
    use HasFactory;

    protected $fillable = [
        'name','start_time','end_time',
    ];
}

resources/views/FS/Reports/index.blade.php
@extends('layouts.app-master')

@section('content')
    <div class="app-content p-md-4">
        <div class="app-container-xl">
            @if (Session::has('error'))
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>{{ Session::get('error') }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
            @if (Session::has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ Session::get('success') }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
            <div class="row g-3 mb-4 align-items-center justify-content-between">
                <div class="col-auto">
                    <h1 class="app-page-title mb-0">รายงานสรุปงาน Stock FS</h1>
                </div>
                <div class="col-auto">
                    <div class="page-utilities">
                        <div class="row g-2 justify-content-start justify-content-md-end align-items-center">
                            <div class="col-auto">
                                <a class="btn app-btn-secondary" href="{{ route('FsReports.fsstockuseemail') }}">
                                    <i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;
                                    Sent Mail
                                </a>
                                {{-- <a class="btn app-btn-secondary" href="{{ route('wh_act.create') }}">
                                    <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
                                    Add
                                </a> --}}
                            </div>
                        </div><!--//row-->
                    </div><!--//table-utilities-->
                </div><!--//col-auto-->
            </div><!--//row onclick="getURL($key);" -->

            <nav class="orders-table-tab app-nav-tabs nav shadow-sm flex-column flex-sm-row mb-4">
                <a class="flex-sm-fill text-sm-center nav-link active" data-bs-toggle="tab" href="#" role="tab"
                    aria-controls="orders-all" aria-selected="true"></a>
            </nav>
            @foreach ($data as $key => $item)
            <div class="row">
                <div class="col-6">
                    <h3>{{  $item->name }}</h3>
                </div>
            </div>
            <div class="row">

                <div class="col-6">
                    @if (isset($chartname[$key]['bar']['link']))
                        <img src="/whform/{{$chartname[$key]['bar']['link']}}" >
                    @else
                        ไม่มีข้อมูล
                    @endif
                </div>
                <div class="col-6">
                    @if (isset($queries[$key]))
                    <div class="tab-content" id="orders-table-tab-content">
                        <div class="app-card app-card-orders-table shadow-sm mb-5">
                            <div class="app-card-body">
                                <table class="table app-table-hover mb-0 text-left">
                                    <thead>
                                        <tr>
                                            <th class="cell">สินค้า</th>
                                            <th class="cell" >จำนวน</th>
                                        </tr>
                                    </thead>
                                    <tbody>

                                        @foreach ($queries[$key] as $fsdata)
                                            <tr>
                                                <td>{{ $fsdata->name }}</td>
                                                <td>{{ number_format($fsdata->volumn) }}</td>
                                            </tr>
                                        @endforeach
                                    </tbody>
                                </table>
                            </div><!--//app-card-body-->
                        </div><!--//app-card-->
                    </div><!--//tab-content-->
                    @else
                        ไม่มีข้อมูล
                    @endif

                </div>

            </div>
            @endforeach


        </div><!--//container-fluid-->
    </div><!--//app-content-->
@endsection