routes/web.php
<?php

use App\Http\Controllers\TR\Test\Test_TRController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\WhDepsController;
use App\Http\Controllers\JobDatasController;
use App\Http\Controllers\WhActsContoller;
// use App\Http\Controllers\HomeController;
use App\Http\Controllers\RegisterController;
// use App\Http\Controllers\LoginController;
// use App\Http\Controllers\LogoutController;
use App\Http\Controllers\ProductInputController;
use App\Http\Controllers\UserTypeController;
use App\Http\Controllers\ForkliftController;
use App\Http\Controllers\FlocationController;
use App\Http\Controllers\FpeopleController;
use App\Http\Controllers\WhActTypeController;
use App\Http\Controllers\FLogController;
use App\Http\Controllers\RecvRmOtherPlansController;
use App\Http\Controllers\RmManualController;
use App\Http\Controllers\StProductController;
use App\Http\Controllers\StWhBeginController;
use App\Http\Controllers\StBrokerController;
use App\Http\Controllers\StReceiveController;
use App\Http\Controllers\StWhithdrawController;


use App\Http\Controllers\FS\ShiftController;
use App\Http\Controllers\FS\ProductController;
use App\Http\Controllers\FS\StoreController;
use App\Http\Controllers\FS\StepController;
use App\Http\Controllers\FS\StepTgController;
use App\Http\Controllers\FS\LoseTypeController;
use App\Http\Controllers\FS\ToReuseController;
use App\Http\Controllers\FS\WashController;
use App\Http\Controllers\FS\DryController;
use App\Http\Controllers\FS\ShineController;
use App\Http\Controllers\FS\ChooseBoxController;
use App\Http\Controllers\FS\StockController;
use App\Http\Controllers\FS\ToUseController;
use App\Http\Controllers\FS\LoseController;
use App\Http\Controllers\FS\TargetController;
use App\Http\Controllers\FS\TargetProductController;
use App\Http\Controllers\FS\ReportController;

//Stock FS WH part
use App\Http\Controllers\Fs\FsWhsController;
use App\Http\Controllers\Fs\FsStocksController;
use App\Http\Controllers\FS\FsReportsController;

use App\Http\Controllers\HandheldImportsController;
use App\Http\Controllers\TR\CalendarController;
//Track Schedule Management
use App\Http\Controllers\TR\TrucksController;
use App\Http\Controllers\TR\ImpDeliveryPlansController;
use App\Http\Controllers\TR\ScheduleTrucksController;
use App\Http\Controllers\TR\TailsController;
use App\Http\Controllers\TR\VesselLinesController;
use App\Http\Controllers\TR\HolidaysController;
use App\Http\Controllers\TR\SumaryController;
use App\Http\Controllers\TR\WeekendsController;

//TEST WHRM
use App\Http\Controllers\WHRM\BeanController;
use App\Http\Controllers\WHRM\TestController;
use App\Http\Controllers\WHRM\BananaController;
use App\Http\Controllers\WHRM\setting\WhRmBrokerAreaController;
use App\Http\Controllers\WHRM\WhRmController;
use App\Http\Controllers\WHRM\WhRmDeleteController;
use App\Http\Controllers\WHRM\WhRmEmailController;
use App\Http\Controllers\WHRM\WhRmImportFileController;
use App\Http\Controllers\WHRM\WhRmReportController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::group(['namespace' => 'App\Http\Controllers'], function () {
    /**
     * Home Routes
     */
    Route::get('/', 'HomeController@index')->name('home.index');

    Route::resource('whdeps', 'WhDepsController');
    Route::resource('jobdatas', 'JobDatasController');

    Route::get('/whacts/planvsactrpt/{date}', 'WhActsContoller@planvsactrpt');

    Route::group(['middleware' => ['guest']], function () {
        /**
         * Register Routes
         */
        Route::get('/register', 'RegisterController@show')->name('register.show');
        Route::post('/register', 'RegisterController@register')->name('register.perform');
        /**
         * Login Routes
         */
        Route::get('/login', 'LoginController@show')->name('login.show');
        Route::post('/login', 'LoginController@login')->name('login.perform');
    });

    Route::group(['middleware' => ['auth']], function () {
        /**
         * Logout Routes
         */
        Route::get('/logout', 'LogoutController@perform')->name('logout.perform');
    });
});

Route::get('/user/delete/{id}', [RegisterController::class, 'destroy'])->name('user_delete');
Route::resource('user', RegisterController::class);

Route::get('/pd_input/importExportView', [ProductInputController::class, 'importExportView'])->name('pd_import_export');
Route::post('/pd_input/import/{tbl}', [ProductInputController::class, 'import'])->name('pd_import');
Route::get('/pd_input/reportView', [ProductInputController::class, 'reportView'])->name('pd_report');
Route::get('/pd_input/report_show', [ProductInputController::class, 'report_export'])->name('pd_show');
Route::get('/pd_input/file_delete/{id}', [ProductInputController::class, 'destroy'])->name('pd_delete');    //delete file
Route::get('/pd_input/list_delete/{type}/{id}', [ProductInputController::class, 'list_destroy'])->name('pd_list_delete');    //delete list
Route::get('/pd_input/mail/{tbl}/{date_to}', [ProductInputController::class, 'sentmail'])->name('pd_sentmail');
Route::get('/pd_input/sum_mail/{date_to}', [ProductInputController::class, 'sum_mail']);
Route::get('/pd_input/sum_mail_month', [ProductInputController::class, 'sum_mail_month']);
Route::resource('pd_input', ProductInputController::class);

Route::resource('/setting/user_type', UserTypeController::class);

Route::get('/setting/forklift/importExportView', [ForkliftController::class, 'importExportView'])->name('forklift_import_export');
Route::post('/setting/forklift/import', [ForkliftController::class, 'import'])->name('forklift_import');
Route::resource('/setting/forklift', ForkliftController::class);

Route::resource('/setting/location', FlocationController::class);
Route::resource('/setting/people', FpeopleController::class);

Route::get('/setting/WhAct_type/importExportView', [WhActTypeController::class, 'importExportView'])->name('WhAct_type_import_export');
Route::post('/setting/WhAct_type/import', [WhActTypeController::class, 'import'])->name('WhAct_type_import');
Route::resource('/setting/WhAct_type', WhActTypeController::class);

Route::get('/FL/FL_del/{date}', [FLogController::class, 'destroy_date'])->name('FL_del');    //delete file
Route::get('/FL/importExportView', [FLogController::class, 'importExportView'])->name('FL_import_export');
Route::post('/FL/import', [FLogController::class, 'import'])->name('FL_import');
Route::get('/FL/reportView', [FLogController::class, 'reportView'])->name('FL_report');
Route::get('/FL/report_show', [FLogController::class, 'report_export'])->name('FL_show');
// Route::get('/FL/mail/{date_to}', [FLogController::class, 'sentmail'])->name('FL_sentmail');
Route::get('/FL/mailView', [FLogController::class, 'mailView'])->name('FL_mail');
Route::get('/FL/sent_mail', [FLogController::class, 'sent_mail'])->name('FL_sent_mail');
Route::get('/FL/atc_search', [FLogController::class, 'selectfl'])->name('FL_autocomplete');
Route::get('/FL/cmb_area', [FLogController::class, 'cmb_area'])->name('FL_area');
Route::get('/FL/cmb_person', [FLogController::class, 'cmb_person'])->name('FL_person');
Route::get('/FL/cmb_broken', [FLogController::class, 'cmb_broken'])->name('FL_broken');
Route::resource('FL', FLogController::class);


Route::get('/recvrmotherplans/changeStatus/{id}', [RecvRmOtherPlansController::class, 'changeStatus'])->name('recvrmotherplans.changestatus');
Route::resource('recvrmotherplans', RecvRmOtherPlansController::class);

Route::get('/wh_act/importExportView', [WhActsContoller::class, 'importExportView'])->name('wh_act_import_export');
Route::post('/wh_act/import_plan', [WhActsContoller::class, 'import_plan'])->name('wh_act_import_plan');
Route::post('/wh_act/import_act', [WhActsContoller::class, 'import_act'])->name('wh_act_import_act');
Route::get('/wh_act/reportView', [WhActsContoller::class, 'reportView'])->name('wh_act_report');
Route::get('/wh_act/report_show', [WhActsContoller::class, 'report_export'])->name('wh_act_show');
Route::get('/wh_act/mailView', [WhActsContoller::class, 'mailView'])->name('wh_act_mail');
Route::get('/wh_act/sent_mail', [WhActsContoller::class, 'sent_mail'])->name('wh_act_sent_mail');
Route::get('/wh_act/del/{date}', [WhActsContoller::class, 'destroy_date'])->name('wh_act_del');    //delete file ลบทั้ง plan และ act จากปุ่มถังขยะหน้า index
Route::post('/wh_act/del_import', [WhActsContoller::class, 'destroy_import'])->name('wh_act_del_import');    //ลบโดยเลือกว่าลบจากอะไร plan/act ที่หน้า import
// Route::get('/wh_act/note/{st}/{pd}/{note}', [WhActsContoller::class, 'save_note']);
Route::get('/wh_act/note', [WhActsContoller::class, 'save_note']);
Route::resource('wh_act', WhActsContoller::class);

Route::get('/wh_rm/importExportView', [RmManualController::class, 'importExportView'])->name('wh_rm_import_export');
Route::post('/wh_rm/import_sap', [RmManualController::class, 'import_sap'])->name('wh_rm_import_sap');
Route::get('/wh_rm/export_manual', [RmManualController::class, 'export_manual'])->name('wh_rm_export_manual');
Route::post('/wh_rm/import_manual', [RmManualController::class, 'import_manual'])->name('wh_rm_import_manual');
Route::post('/wh_rm/export_sap', [RmManualController::class, 'import_comment'])->name('wh_rm_import_comment');
Route::get('/wh_rm/reportView', [RmManualController::class, 'reportView'])->name('wh_rm_report');
Route::get('/wh_rm/report_show', [RmManualController::class, 'report_export'])->name('wh_rm_show');
Route::get('/wh_rm/mailView', [RmManualController::class, 'mailView'])->name('wh_rm_mail');

app/Http/Controllers/WHRM/setting/WhRmBrokerAreaController.php
<?php

namespace App\Http\Controllers\WHRM\setting;

use App\Http\Controllers\Controller;
use App\Models\RmArea;
use App\Models\RmBroker;
use App\Models\RmBrokerAears;
use Illuminate\Http\Request;

class WhRmBrokerAreaController extends Controller
{
    public function index()
    {
        $perpage = 20;
        $rm_broker_areas = RmBrokerAears::orderBy('created_at', 'DESC')
            ->paginate($perpage);

        $rmBrokers = RmBroker::whereDoesntHave('rmBrokerAreas')->pluck('name', 'id');
        $rmAears = RmArea::pluck('name', 'id');

        $brokers = RmBroker::pluck('name', 'id');
        $areas = RmArea::pluck('name', 'id');

        return view('TEST.setting.index', compact(
            'rm_broker_areas',
            'rmBrokers',
            'rmAears',
            'brokers',
            'areas',
        ));
    }

    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        RmBrokerAears::create([
            'rm_broker_id' => $request->broker,
            'rm_area_id' => $request->area,
        ]);

        return redirect()->back()->with('success', 'บันทึกสำเร็จ ');
    }


    public function show($id)
    {
        //
    }

    public function edit($id)
    {
    }

    public function update(Request $request, $id)
    {
        RmBrokerAears::findOrFail($id)->update([
            'rm_broker_id' => $request->broker,
            'rm_area_id' => $request->area,
        ]);
        return redirect()->back()->with('success', 'แก้ไขสำเร็จ ');
    }

    public function destroy($id)
    {
        //
    }


    public function whrmSettingAddBroker(Request $request)
    {
        RmBroker::create(['name' => $request->name]);
        return redirect()->back()->with('success', 'เพิ่ม Broker สำเร็จ ');
    }


    public function whrmSettingAddArea(Request $request)
    {
        RmArea::create(['name' => $request->name]);
        return redirect()->back()->with('success', 'เพิ่ม Area สำเร็จ ');
    }
}

resources/views/setting/people/create.blade.php
@extends('layouts.app-master')

@section('content')
    <div class="app-content p-md-4">
        <div class="app-container-xl">
            <div class="page-heading row">        
                <div class="pull-right col-auto">
                    <a class="btn btn-success" href="{{ route('people.index') }}">Back</a>
                </div>
                <h3 class="col">{{ __('พนักงาน') }} -> Create</h3>
            </div>
        
            <nav class="orders-table-tab app-nav-tabs nav shadow-sm flex-column flex-sm-row mb-4">
                <a class="flex-sm-fill text-sm-center nav-link active" data-bs-toggle="tab" href="#" role="tab"
                    aria-controls="orders-all" aria-selected="true"></a>
            </nav>  
            
            <div class="tab-content" id="orders-table-tab-content">                
                <div class="app-card app-card-orders-table shadow-sm mb-5">
                    <div class="app-card-body">
                        <form method="POST" action="{{ route('people.store') }}">
                            @csrf
                            <div class="form-group row mb-2">
                                <label for="fname" class="col-md-2 col-form-label text-md-right">{{ __('คำนำหน้าและชื่อ') }}</label>

                                <div class="col-md-6">
                                    <input id="fname" type="text" class="form-control @error('fname') is-invalid @enderror"
                                        name="fname" value="{{ old('fname') }}" required autocomplete="name" autofocus>

                                    @error('fname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>  
                            
                            <div class="form-group row mb-2">
                                <label for="lname" class="col-md-2 col-form-label text-md-right">{{ __('นามสกุล') }}</label>

                                <div class="col-md-6">
                                    <input id="lname" type="text" class="form-control @error('lname') is-invalid @enderror"
                                        name="lname" value="{{ old('lname') }}" required autocomplete="name" autofocus>

                                    @error('lname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div> 

                            <div class="form-group row mb-2">
                                <div class="col-md-6 offset-md-2">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Save') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div><!--//app-card-body-->		
                </div><!--//app-card-->                  
            </div><!--//tab-content-->
        </div><!--//container-fluid-->
    </div><!--//app-content-->        
@endsection

resources/views/setting/people/edit.blade.php
@extends('layouts.app-master')

@section('content')
    <div class="app-content p-md-4">
        <div class="app-container-xl">
            <div class="page-heading row">        
                <div class="pull-right col-auto">
                    <a class="btn btn-success" href="{{ route('people.index') }}">Back</a>
                </div>
                <h3 class="col">{{ __('พนักงาน') }} -> Edit</h3>
            </div>
        
            <nav class="orders-table-tab app-nav-tabs nav shadow-sm flex-column flex-sm-row mb-4">
                <a class="flex-sm-fill text-sm-center nav-link active" data-bs-toggle="tab" href="#" role="tab"
                    aria-controls="orders-all" aria-selected="true"></a>
            </nav>  
            
            <div class="tab-content" id="orders-table-tab-content">                
                <div class="app-card app-card-orders-table shadow-sm mb-5">
                    <div class="app-card-body">
                        <form method="POST" action="{{ route('people.update', $people->id) }}">
                            @csrf
                            @method('PUT')
                            <div class="form-group row mb-2">
                                <label for="fname" class="col-md-2 col-form-label text-md-right">{{ __('คำนำหน้าและชื่อ') }}</label>

                                <div class="col-md-6">
                                    <input id="fname" type="text" class="form-control @error('fname') is-invalid @enderror"
                                        name="fname" value="{{ $people->fname }}" required autocomplete="name" autofocus>

                                    @error('fname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div> 
                            
                            <div class="form-group row mb-2">
                                <label for="lname" class="col-md-2 col-form-label text-md-right">{{ __('นามสกุล') }}</label>

                                <div class="col-md-6">
                                    <input id="lname" type="text" class="form-control @error('lname') is-invalid @enderror"
                                        name="lname" value="{{ $people->lname }}" required autocomplete="lname" autofocus>

                                    @error('lname')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div> 

                            <div class="form-group row mb-2">
                                <div class="col-md-6 offset-md-2">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Save') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div><!--//app-card-body-->		
                </div><!--//app-card-->                  
            </div><!--//tab-content-->
        </div><!--//container-fluid-->
    </div><!--//app-content-->     
@endsection

resources/views/setting/people/index.blade.php
@extends('layouts.app-master')

@section('content')
    <div class="app-content p-md-4">
        <div class="app-container-xl">
            @if(Session::has('error'))
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>{{ Session::get('error') }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
            @if(Session::has('success'))
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>{{ Session::get('success') }}</strong>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            @endif
            <div class="row g-3 mb-4 align-items-center justify-content-between">
                <div class="col-auto">
                    <h1 class="app-page-title mb-0">พนักงาน</h1>
                </div>
                <div class="col-auto">
                    <div class="page-utilities">
                        <div class="row g-2 justify-content-start justify-content-md-end align-items-center">
                            <div class="col-auto">						    
                                {{-- <a class="btn app-btn-secondary" href="{{ route('pd_import_export') }}">
                                    <i class="fas fa-file-upload"></i>&nbsp;
                                    Upload Excel
                                </a> --}}
                                <a class="btn app-btn-secondary" href="{{ route('people.create') }}">
                                    <i class="fa fa-plus" aria-hidden="true"></i>&nbsp;
                                    Add
                                </a>
                            </div>
                        </div><!--//row-->
                    </div><!--//table-utilities-->
                </div><!--//col-auto-->
            </div><!--//row onclick="getURL($key);" -->
        
            <nav class="orders-table-tab app-nav-tabs nav shadow-sm flex-column flex-sm-row mb-4">
                <a class="flex-sm-fill text-sm-center nav-link active" data-bs-toggle="tab" href="#" role="tab"
                    aria-controls="orders-all" aria-selected="true"></a>
            </nav>             
            
            <div class="tab-content" id="orders-table-tab-content">                
                <div class="app-card app-card-orders-table shadow-sm mb-5">
                    <div class="app-card-body">
                        <div class="table-responsive">
                            <table class="table app-table-hover mb-0 text-left">
                                <thead>
                                    <tr>
                                        <th class="cell">No.</th>
                                        <th class="cell">Name</th>
                                        <th class="cell"></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($people as $key)
                                        <tr>                                             
                                            <td class="cell">{{ $loop->iteration }}</td>
                                            <td class="cell">{{ $key->fname }} {{ $key->lname }}</td>
                                            <td class="row">
                                                <div class="col-auto mx-2">
                                                    <a class="btn btn-primary" href="{{ route('people.edit', $key->id) }}">Edit</a>
                                                </div>
                                                <div class="col-auto">
                                                    <form action="{{ route('people.destroy', $key->id) }}" method="POST">
                                                        @csrf
                                                        @method('DELETE')
                                                        <button type="submit" class="btn btn-danger">Delete</button>
                                                    </form>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div><!--//table-responsive-->                            
                    </div><!--//app-card-body-->		
                </div><!--//app-card-->                  
            </div><!--//tab-content-->
        </div><!--//container-fluid-->
    </div><!--//app-content-->
@endsection